### ISSUE TITLE
Undefined method using EventedSpec::EMSpec

### ISSUE THREAD

**Issue by emschwar** [ruby-amqp/evented-spec#6]
I have a spec, `spec/a_spec.rb`:

```ruby
require 'rspec'
require 'evented-spec'

describe "a thing" do
  include EventedSpec::EMSpec

  it "does stuff" do
    expect(1).to eq(1)
  end
end
```

If I run it with the latest master of evented-spec, I get:

```
/usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:675:in `method_missing': undefined local variable or method `args_block' for RSpec::ExampleGroups::AThing:Class (NameError)
        from /usr/local/lib/ruby/gems/2.3.0/bundler/gems/evented-spec-7dd6d246285a/lib/evented-spec/em_spec.rb:20:in `it'
        from /private/tmp/foo/spec/a_spec.rb:7:in `block in <top (required)>'
        from /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:385:in `module_exec'
        from /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:385:in `subclass'
        from /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:255:in `block in define_example_group_method'
        from /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/dsl.rb:43:in `block in expose_example_group_alias'
        from /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/dsl.rb:82:in `block (2 levels) in expose_example_group_alias_globally'
        from /private/tmp/foo/spec/a_spec.rb:4:in `<top (required)>'
        from /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load'
        from /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
        from /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
        from /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
        from /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
        from /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
        from /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
        from /usr/local/bin/rspec:23:in `load'
        from /usr/local/bin/rspec:23:in `<main>'
```

I believe this is a result of https://github.com/ruby-amqp/evented-spec/blob/master/lib/evented-spec/em_spec.rb#L20, where the variable `args_block` isn't available outside of the `new_block` lambda. Since I'm not entirely clear on why that change was made in the first place, I'm not yet ready to propose a fix.

**Comment by zhenkyle** [comment]
Sorry, I made mistakes in Fix #4 which purpose is to  kill some warnings.

It's a minor fix so I didn't do any test. It's another lesson we shouldn't trust code not tested.  I just add a commit to fix this problem. This time, I did do test. 

However `bundle exec rspec spec/evented-spec/adapters/em_spec.rb` did passed, but `bundle exec rspec spec/evented-spec/adapters/amqp_spec.rb` and `bundle exec rspec spec/evented-spec/adapters/cool_io_spec.rb` did not. After investigate, I think it shouldn't be problem caused by this fix commit, there could be  some gem version problem in :test group of Gemfile, but I couldn't  figure it out.
